// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.ComponentModel;

namespace Stratum
{

    internal partial class StratumResult
    {

        [JsonProperty("id")]
        public int? Id { get; set; }

        [JsonProperty("result")]
        public object Result { get; set; }

        [JsonProperty("error")]
        public object[] Error { get; set; }

        public StratumResult(int id, object result, object error)
        {
            this.Id = id;
            this.Result = result;
            this.Error = (object[])error;
        }
    }

}
